language: minimal

services:
  - docker

branches:
  only:
    - source

before_install:
  - docker build -t zola .

script:
  - docker run --rm -v "$PWD":/blog zola build

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  fqdn: gkudelis.net
  local_dir: public
  target_branch: master
  on:
    branch: source
