sudo: false
language: haskell
branches:
  only:
    - source
cache:
  directories:
    - "$HOME/.stack"
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
  - stack --install-ghc install hakyll
  - stack build
before_script:
  - cd _site
  - git checkout master
  - git pull origin master
  - cd ..
script: stack exec site build
after_script:
  - cd _site
  - git status
  - git add --all
  - git config --global user.email "giedrius.kudelis@gmail.com"
  - git config --global user.name "Travis CI"
  - git commit -m "Snapshot $(date '+%m/%d/%Y %H:%M')"
  - git status
  - git push "$REPO_URL" master | grep -v http
  - cd ..
group: stable
dist: precise
os: linux
env:
  global:
    - secure: "KsGQyBs3eLt351loIgDG+4W2wVuWHpyHmaHVqjficIW+gxLqxNvvGN6UdKO4i7dSBzD+2lLv+NLgJBH5bo3wReLiuO1jkLO++nuy4MDZNwNYwdCy5E9TaHqVrvmmmA/hbMfiylGCnI3fbwmeqxHcMNBEUUfpXXcjoaW4uAJjiXMQUk5XI7xgaSFosOM/SKSzENUui+jmRmxeic11Q7KVWVt8FQzwn6ANdfGh0nfkFjHMS5Tf/UebaDz+D2V2MP9afl5Cl+XP+llfS52H50R9tAaiOiaLxQpF7woPTZTxsSyaemvgnsxHqfrtU7JQ+27DvRd42rdI/j7X8a41E5DRrj7PsDk1x8iyUEpudTNNcxRdY9z8Es0EcZL6HqV4He3vLK4157r55/7wGOhV2TDoDi8MvPnmtPJ+5QfPdqz3onspoR8PLBl1/GJ879W+d0wonNTzR6xAbqVpT3JzSuapeK9DcthtbLpoOQ1w5OblzoRyQcBL22r2WCIE/4BXAitMHN9eAGmGDHPasx1xaiy8L8OOfmi8Ut4IuAtq0xuGI2aKM9C91ddqg7JSRNDQgMfmxk6WBC8Q0TJ6Z7bIyVpPgwN9yS4r4ZdDyDnBiD8Tyi9XqKvg7Dnp0NGSOa1ELGazTUiFry5eHUtjNKoQIRfWTx7CPN4am4i2jiQR3Zl6OAs="
