sudo: false
language: generic
services:
  - docker
branches:
  only:
    - source
cache:
  directories:
    - "$HOME/.stack"
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
  - stack docker pull
  - stack build
script: stack run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  fqdn: gkudelis.net
  target_branch: master
  on:
    branch: source
