FROM ubuntu
WORKDIR /app
RUN apt update && apt install -y curl
RUN curl -L https://github.com/getzola/zola/releases/download/v0.8.0/zola-v0.8.0-x86_64-unknown-linux-gnu.tar.gz | tar xz -C /usr/bin
RUN 
