on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and publish
        uses: .github/actions/publish
